# Generated by Django 6.0.5 on 2026-06-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_book_similar_books_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='similar_books',
            field=models.ManyToManyField(blank=True, related_name='+', to='core.book'),
        ),
    ]
