# Generated by Django 6.0.5 on 2026-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_published_date_book_published_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(help_text='The title of the book', max_length=10, verbose_name='Title'),
        ),
    ]
